version: '3.1'

services:
  
  api: 
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/opt/app:delegated
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGO_URI: "mongodb://mongo:27017/blueprint"
      JWT_SECRET: GLpNfb0b9ypMohara
      JWT_EXPIRATION_MINUTES: 60
    depends_on:
      - mongo
    ports:
      - 3000:3000
    links:
      - mongo 

  mongo:
    image: mongo
    restart: always
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./.docker/mongo-db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    links:
      - mongo
