version: '3.1'

services:
  
  api: 
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/opt/app:delegated
    environment:
      NODE_ENV: production
      PORT: 3000
      MONGO_URI: "mongodb://mongo:27017/mockup"
      JWT_SECRET: GLpNfb0b9ypMohara
      JWT_EXPIRATION_MINUTES: 60
    ports:
      - 3000:3000
